CREATE TABLE IF NOT EXISTS public.student
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address character varying(255) COLLATE pg_catalog."default" NOT NULL,
    branch smallint NOT NULL,
    dob date NOT NULL,
    middle_name character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    parents_mail character varying(255) COLLATE pg_catalog."default",
    parents_phone_number character varying(255) COLLATE pg_catalog."default",
    personal_mail character varying(255) COLLATE pg_catalog."default" NOT NULL,
    personal_phone_number character varying(255) COLLATE pg_catalog."default" NOT NULL,
    roll_no integer NOT NULL,
    school_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    semester character varying(255) COLLATE pg_catalog."default" NOT NULL,
    surname character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT student_pkey PRIMARY KEY (id),
    CONSTRAINT ukrane7utxv14bfxp4wkxesjlsr UNIQUE (roll_no),
    CONSTRAINT student_branch_check CHECK (branch >= 0 AND branch <= 2)
)

CREATE TABLE IF NOT EXISTS public.events
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    event_date date NOT NULL,
    name character varying(255) COLLATE pg_catalog."default",
    type smallint,
    CONSTRAINT events_pkey PRIMARY KEY (id),
    CONSTRAINT events_type_check CHECK (type >= 0 AND type <= 2)
)